RestClients:
  #A simple API to predict the gender of a person given their name
  Genderize.io API (Genderize):
    UUID: f056a122-aaf1-4271-90eb-9d0cc81e0743
    Url: https://api.genderize.io
    Icon: res:/webContent/icons/genderize.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
